language: go
dist: trusty
sudo: false
install: true

addons:
  sonarcloud:
    organization: "sagap-github"
    token:
      secure: "556e44993381632b5fc8a567bb1a1885c4bb7d6a"
jdk:
  - oraclejdk8

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar

cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"
